---
title: List of the Publications
format:
  html:
    css: pubs.css
    page-layout: full
    # toc: true
    # toc_depth: 3
    # toc_float: true
    # toc_smooth_scroll: true
    # toc_highlight: true
    # fig-align: center
    # linkcolor: blue
---

<!-- references -->

## 2025

### Journal articles
1. [Journal]{.pubtype .journal} **Vehicular Cloud Computing: A cost-effective alternative to Edge Computing in 5G networks**. R. Patan\`e, N. Achir, A. Araldo, L. Boukhatem. *Comput. Networks*, 2025. [doi](https://doi.org/10.1016/J.COMNET.2025.111365)

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **The Silent Signature: Behavior-Based User Exposure in Mobility Data**. L. G. S. F\'elix, A. J. Kouam, A. C. Viana, N. Achir, J. M. Almeida. *26th IEEE International Conference on Mobile Data Management, MDM 2025, Irvine, CA, USA, June 2-5, 2025*, 2025. [doi](https://doi.org/10.1109/MDM65600.2025.00044)
1. [Conference]{.pubtype .conf} **MITIK Toolkit: A Privacy-Compliant Passive Collection of WiFi Probe Request Datasets**. F. M. Ortiz, G. Farhi-Rivasseau, N. Achir, A. C. Viana. *Proceedings of the ACM SIGCOMM 2025 Posters and Demos, ACM SIGCOMM Posters and Demos 2025, Coimbra, Portugal, September 8-11, 2025*, 2025. [doi](https://doi.org/10.1145/3744969.3748453)
1. [Conference]{.pubtype .conf} **Enhancing Split ViT Inference Through Sparsity-Driven Compression**. A. Dhaouadi, N. Achir, C. Adjih. *101st IEEE Vehicular Technology Conference, VTC Spring 2025, Oslo, Norway, June 17-20, 2025*, 2025. [doi](https://doi.org/10.1109/VTC2025-SPRING65109.2025.11174366)

### Technical reports
1. [Report]{.pubtype .report} **Vehicular Cloud Computing: A cost-effective alternative to Edge Computing in 5G networks**. R. Patan\`e, N. Achir, A. Araldo, L. Boukhatem. *CoRR*, 2025. [pdf](https://arxiv.org/pdf/2507.15670.pdf)
1. [Report]{.pubtype .report} **Can vehicular cloud replace edge computing?**. R. Patan\`e, N. Achir, A. Araldo, L. Boukhatem. *CoRR*, 2025. [pdf](https://arxiv.org/pdf/2501.04702.pdf)
1. [Report]{.pubtype .report} **BUBBLE-BLUE a multihop private network based on Bluetooth**. N. Achir, P. Jacquet. *CoRR*, 2025. [pdf](https://arxiv.org/pdf/2509.00967.pdf)

## 2024

### Journal articles
1. [Journal]{.pubtype .journal} **Bleach: From WiFi probe-request signatures to MAC association**. A. K. Mishra, A. C. Viana, N. Achir. *Ad Hoc Networks*, 2024. [doi](https://doi.org/10.1016/J.ADHOC.2024.103623)

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Can vehicular cloud replace edge computing?**. R. Patan\`e, N. Achir, A. Araldo, L. Boukhatem. *WCNC 2024 - IEEE Wireless Communications and Networking Conference*, 2024. [pdf](https://hal.science/hal-04393593/file/wcnc_2024_Vehicloud-2.pdf)
1. [Conference]{.pubtype .conf} **AutoMHS-GPT: Automated Model and Hyperparameter Selection with Generative Pre-Trained Model**. L. A. C. de Souza, M. Sammarco, N. Achir, M. E. M. Campista, L. H. M. K. Costa. *13th IEEE International Conference on Cloud Networking, CloudNet 2024, Rio de Janeiro, Brazil, November 27-29, 2024*, 2024. [doi](https://doi.org/10.1109/CLOUDNET62863.2024.10815898)

## 2023

### Journal articles
1. [Journal]{.pubtype .journal} **On the Edge of the Deployment: A Survey on Multi-access Edge Computing**. P. Cruz, N. Achir, A. C. Viana. *ACM Comput. Surv.*, 2023. [doi](https://doi.org/10.1145/3529758)

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Introducing benchmarks for evaluating user-privacy vulnerability in WiFi**. A. K. Mishra, A. C. Viana, N. Achir. *97th IEEE Vehicular Technology Conference, VTC Spring 2023, Florence, Italy, June 20-23, 2023*, 2023. [doi](https://doi.org/10.1109/VTC2023-SPRING57618.2023.10199706)
1. [Conference]{.pubtype .conf} **Impact of User Privacy and Mobility on Edge Offloading**. J. P. Esper, N. Achir, K. V. Cardoso, J. M. Almeida. *34th IEEE Annual International Symposium on Personal, Indoor and Mobile Radio Communications PIMRC 2023, Toronto, ON, Canada, September 5-8, 2023*, 2023. [doi](https://doi.org/10.1109/PIMRC56721.2023.10293816)
1. [Conference]{.pubtype .conf} **Do WiFi Probe-Requests Reveal Your Trajectory?**. A. K. Mishra, A. C. Viana, N. Achir. *IEEE Wireless Communications and Networking Conference, WCNC 2023, Glasgow, UK, March 26-29, 2023*, 2023. [doi](https://doi.org/10.1109/WCNC55385.2023.10118635)
1. [Conference]{.pubtype .conf} **Analyzing and Optimizing Extended-CAM Service Using Simple Stochastic Geometry Model**. P. Muhlethaler, N. Achir. *12th IFIP/IEEE International Conference on Performance Evaluation and Modeling in Wired and Wireless Networks, PEMWN 2023, Berlin, Germany, September 27-29, 2023*, 2023. [doi](https://doi.org/10.23919/PEMWN58813.2023.10304925)

### Technical reports
1. [Report]{.pubtype .report} **Impact of User Privacy and Mobility on Edge Offloading**. J. P. Esper, N. Achir, K. V. Cardoso, J. M. Almeida. *CoRR*, 2023. [pdf](https://arxiv.org/pdf/2306.15740.pdf)

## 2022

### Journal articles
1. [Journal]{.pubtype .journal} **Online drone-based data gathering strategies for ground sensor networks**. C. Y. Tazibt, N. Achir, T. Djamah. *Int. J. Sens. Networks*, 2022. [doi](https://doi.org/10.1504/IJSNET.2022.121702)

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Performance Analysis of a Privacy-Preserving Frame Sniffer on a Raspberry Pi**. F. D. D. M. Silva, A. K. Mishra, A. C. Viana, N. Achir, A. Fladenmuller, L. H. M. K. Costa. *6th Cyber Security in Networking Conference, CSNet 2022, Rio de Janeiro, Brazil, October 24-26, 2022*, 2022. [doi](https://doi.org/10.1109/CSNET56116.2022.9955615)

## 2021

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Public Wireless Packets Anonymously Hurt You**. A. K. Mishra, A. C. Viana, N. Achir, C. Palamidessi. *46th IEEE Conference on Local Computer Networks, LCN 2021, Edmonton, AB, Canada, October 4-7, 2021*, 2021. [doi](https://doi.org/10.1109/LCN52139.2021.9524956)
1. [Conference]{.pubtype .conf} **Increasing vehicles perception using cooperative relaying and priority-based beaconing**. S. Faiz, N. Achir, K. Boussetta. *22nd IEEE International Conference on High Performance Switching and Routing, HPSR 2021, Paris, France, June 7-10, 2021*, 2021. [doi](https://doi.org/10.1109/HPSR52026.2021.9481799)
1. [Conference]{.pubtype .conf} **Dynamic Hierarchical Neural Network Offloading in IoT Edge Networks**. W. Seifeddine, C. Adjih, N. Achir. *10th IFIP International Conference on Performance Evaluation and Modeling in Wireless and Wired Networks, PEMWN 2021, Waterloo, ON, Canada, November 23-25, 2021*, 2021. [doi](https://doi.org/10.23919/PEMWN53042.2021.9664700)
1. [Conference]{.pubtype .conf} **Associating the Randomized Bluetooth MAC Addresses of a Device**. L. Jouans, A. C. Viana, N. Achir, A. Fladenmuller. *18th IEEE Annual Consumer Communications \& Networking Conference, CCNC 2021, Las Vegas, NV, USA, January 9-12, 2021*, 2021. [doi](https://doi.org/10.1109/CCNC49032.2021.9369628)

### Technical reports
1. [Report]{.pubtype .report} **SimBle: Generating privacy preserving real-worldBLE traces with ground truth**. A. K. Mishra, A. C. Viana, N. Achir. *CoRR*, 2021. [pdf](https://arxiv.org/pdf/2101.11728.pdf)

## 2020

### Journal articles
1. [Journal]{.pubtype .journal} **Special issue on multimedia fog/edge computing systems**. Y. Jin, D. D'Agostino, N. Achir, J. Nightingale, J. Wang. *Multim. Syst.*, 2020. [doi](https://doi.org/10.1007/S00530-019-00643-7)

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **On the benefits of increased vehicles perception to cooperative communications: a performance evaluation study**. S. Faiz, N. Achir, K. Boussetta. *MobiArch@MobiCom 2020: Proceedings of the 15th Workshop on Mobility in the Evolving Internet Architecture, London, United Kingdom, September 21, 2020*, 2020. [doi](https://doi.org/10.1145/3411043.3412504)
1. [Conference]{.pubtype .conf} **Fog Services Provider Architecture for IoT**. H. Le, N. Achir, K. Boussetta. *11th International Conference on Network of the Future, NoF 2020, Bordeaux, France, October 12-14, 2020*, 2020. [doi](https://doi.org/10.1109/NOF50125.2020.9249177)
1. [Conference]{.pubtype .conf} **A unified and semantic data model for fog computing**. H. Le, K. Boussetta, N. Achir. *Global Information Infrastructure and Networking Symposium, GIIS 2020, Tunis, Tunisia, October 28-30, 2020*, 2020. [doi](https://doi.org/10.1109/GIIS50753.2020.9248482)

## 2019

### Journal articles
1. [Journal]{.pubtype .journal} **Maximizing mobiles energy saving through tasks optimal offloading placement in two-tier cloud: A theoretical and an experimental study**. H. Mazouzi, K. Boussetta, N. Achir. *Comput. Commun.*, 2019. [doi](https://doi.org/10.1016/J.COMCOM.2019.05.017)
1. [Journal]{.pubtype .journal} **Guest editorials: Special issue on fog/edge networking for multimedia applications**. Y. Jin, H. Shen, D. D'Agostino, N. Achir, J. Nightingale. *Peer-to-Peer Netw. Appl.*, 2019. [doi](https://doi.org/10.1007/S12083-019-00812-5)
1. [Journal]{.pubtype .journal} **DM2-ECOP: An Efficient Computation Offloading Policy for Multi-user Multi-cloudlet Mobile Edge Computing Environment**. H. Mazouzi, N. Achir, K. Boussetta. *ACM Trans. Internet Techn.*, 2019. [doi](https://doi.org/10.1145/3241666)

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Proactive Network Slices Management Algorithm Based on Fuzzy Logic System and Support Vector Regression Model**. A. Kammoun, N. Tabbane, G. Diaz, N. Achir, A. Dandoush. *Advances on Broad-Band Wireless Computing, Communication and Applications- Proceedings of the 14th International Conference on Broad-Band Wireless Computing, Communication and Applications, BWCCA 2019, Antwerp, Belgium, November 7-9, 2019*, 2019. [doi](https://doi.org/10.1007/978-3-030-33506-9\_34)
1. [Conference]{.pubtype .conf} **Inter-slice Mobility Management in the Context of SDN/NFV Networks**. A. Kammoun, N. Tabbane, G. Diaz, N. Achir, A. Dandoush. *Distributed Computing for Emerging Smart Networks - First International Workshop, DiCES-N 2019, Hammamet, Tunisia, October 30, 2019, Revised Selected Papers*, 2019. [doi](https://doi.org/10.1007/978-3-030-40131-3\_5)
1. [Conference]{.pubtype .conf} **Fog computing architecture with heterogeneous Internet of Things technologies**. H. Le, N. Achir, K. Boussetta. *10th International Conference on Networks of the Future, NoF 2019, Rome, Italy, October 1-3, 2019*, 2019. [doi](https://doi.org/10.1109/NOF47743.2019.9014960)
1. [Conference]{.pubtype .conf} **Elastic Offloading of Multitasking Applications to Mobile Edge Computing**. H. Mazouzi, N. Achir, K. Boussetta. *Proceedings of the 22nd International ACM Conference on Modeling, Analysis and Simulation of Wireless and Mobile Systems, MSWiM 2019, Miami Beach, FL, USA, November 25-29, 2019*, 2019. [doi](https://doi.org/10.1145/3345768.3355926)
1. [Conference]{.pubtype .conf} **Dynamic Handler Framework for Network Slices Management**. A. Kammoun, N. Tabbane, G. Diaz, N. Achir, A. Dandoush. *2019 International Conference on Software, Telecommunications and Computer Networks, SoftCOM 2019, Split, Croatia, September 19-21, 2019*, 2019. [doi](https://doi.org/10.23919/SOFTCOM.2019.8903783)

## 2018

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **UAV-Based Data Gathering Using An Artificial Potential Fields Approach**. C. Y. Tazibt, N. Achir, P. M\"uhlethaler, T. Djamah. *88th IEEE Vehicular Technology Conference, VTC Fall 2018, Chicago, IL, USA, August 27-30, 2018*, 2018. [doi](https://doi.org/10.1109/VTCFALL.2018.8691007)
1. [Conference]{.pubtype .conf} **Maximizing Mobiles Energy Saving Through Tasks Optimal Offloading Placement in two-tier Cloud**. H. Mazouzi, N. Achir, K. Boussetta. *Proceedings of the 21st ACM International Conference on Modeling, Analysis and Simulation of Wireless and Mobile Systems, MSWiM 2018, Montreal, QC, Canada, October 28 - November 02, 2018*, 2018. [doi](https://doi.org/10.1145/3242102.3242133)
1. [Conference]{.pubtype .conf} **End-to-End Efficient Heuristic Algorithm for 5G Network Slicing**. A. Kammoun, N. Tabbane, G. Diaz, A. Dandoush, N. Achir. *32nd IEEE International Conference on Advanced Information Networking and Applications, AINA 2018, Krakow, Poland, May 16-18, 2018*, 2018. [doi](https://doi.org/10.1109/AINA.2018.00065)
1. [Conference]{.pubtype .conf} **Drones path planning for WSN data gathering: A column generation heuristic approach**. M. Garraffa, M. Bekhti, L. L\'etocart, N. Achir, K. Boussetta. *2018 IEEE Wireless Communications and Networking Conference, WCNC 2018, Barcelona, Spain, April 15-18, 2018*, 2018. [doi](https://doi.org/10.1109/WCNC.2018.8377391)
1. [Conference]{.pubtype .conf} **Admission Control Algorithm for Network Slicing Management in SDN-NFV Environment**. A. Kammoun, N. Tabbane, G. Diaz, N. Achir. *6th International Conference on Multimedia Computing and Systems, ICMCS 2018, Rabat, Morocco, May 10-12, 2018*, 2018. [doi](https://doi.org/10.1109/ICMCS.2018.8525945)
1. [Conference]{.pubtype .conf} **A Collaborative Environment Perception Approach for Vehicular Ad Hoc Networks**. S. Ingrachen, N. Achir, P. M\"uhlethaler, T. Djamah, A. Berqia. *88th IEEE Vehicular Technology Conference, VTC Fall 2018, Chicago, IL, USA, August 27-30, 2018*, 2018. [doi](https://doi.org/10.1109/VTCFALL.2018.8690995)

## 2017

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Wireless sensor network clustering for UAV-based data gathering**. C. Y. Tazibt, M. Bekhti, T. Djamah, N. Achir, K. Boussetta. *2017 Wireless Days, Porto, Portugal, March 29-31, 2017*, 2017. [doi](https://doi.org/10.1109/WD.2017.7918154)
1. [Conference]{.pubtype .conf} **Swarm of Networked Drones for Video Detection of Intrusions**. M. Bekhti, N. Achir, K. Boussetta. *Wireless Internet - 10th International Conference, WiCON 2017, Tianjin, China, December 16-17, 2017, Proceedings*, 2017. [doi](https://doi.org/10.1007/978-3-319-90802-1\_19)
1. [Conference]{.pubtype .conf} **Optimized spatial CSMA for VANETs: A comparative study using a simple stochastic model and simulation results**. Y. Bouchaala, P. M\"uhlethaler, O. Shagdar, N. Achir. *14th IEEE Annual Consumer Communications \& Networking Conference, CCNC 2017, Las Vegas, NV, USA, January 8-11, 2017*, 2017. [doi](https://doi.org/10.1109/CCNC.2017.7983122)
1. [Conference]{.pubtype .conf} **Evaluating the gain of directional antennas in linear VANETs using stochastic geometry**. P. M\"uhlethaler, Y. Bouchaala, O. Shagdar, N. Achir. *International Conference on Performance Evaluation and Modeling in Wired and Wireless Networks, PEMWN 2017, Paris, France, November 28-30, 2017*, 2017. [doi](https://doi.org/10.23919/PEMWN.2017.8308021)
1. [Conference]{.pubtype .conf} **Drone Package Delivery: A Heuristic approach for UAVs path planning and tracking**. M. Bekhti, N. Achir, K. Boussetta, M. Abdennebi. *EAI Endorsed Transactions on Internet of Things*, 2017. [doi](https://doi.org/10.4108/eai.31-8-2017.153048)
1. [Conference]{.pubtype .conf} **Assessment of multi-UAVs tracking for data gathering**. M. Bekhti, M. Garraffa, N. Achir, K. Boussetta, L. L\'etocart. *13th International Wireless Communications and Mobile Computing Conference, IWCMC 2017, Valencia, Spain, June 26-30, 2017*, 2017. [doi](https://doi.org/10.1109/IWCMC.2017.7986423)
1. [Conference]{.pubtype .conf} **Analysis of the IEEE 802.11 EDCF scheme for broadcast traffic: Application for VANETs**. Y. Bouchaala, P. M\"uhlethaler, N. Achir. *2017 Wireless Days, Porto, Portugal, March 29-31, 2017*, 2017. [doi](https://doi.org/10.1109/WD.2017.7918156)

## 2016

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Path planning of unmanned aerial vehicles with terrestrial wireless network tracking**. M. Bekhti, M. Abdennebi, N. Achir, K. Boussetta. *2016 Wireless Days, WD 2016, Toulouse, France, March 23-25, 2016*, 2016. [doi](https://doi.org/10.1109/WD.2016.7461521)
1. [Conference]{.pubtype .conf} **Optimisation of spatial CSMA using a simple stochastic geometry model for 1D and 2D networks**. N. Achir, Y. Bouchaala, P. M\"uhlethaler, O. Shagdar. *2016 International Wireless Communications and Mobile Computing Conference (IWCMC), Paphos, Cyprus, September 5-9, 2016*, 2016. [doi](https://doi.org/10.1109/IWCMC.2016.7577118)
1. [Conference]{.pubtype .conf} **Comparison of spatial aloha and CSMA using simple stochastic geometry models for 1D and 2D networks**. N. Achir, Y. Bouchaala, P. M\"uhlethaler, O. Shagdar. *23rd International Conference on Telecommunications, ICT 2016, Thessaloniki, Greece, May 16-18, 2016*, 2016. [doi](https://doi.org/10.1109/ICT.2016.7500470)
1. [Conference]{.pubtype .conf} **Avoiding Collisions by Time Slot Reduction Supporting Voice and Video in 802.11 Networks**. R. A. da Silva, A. Santos, M. Nogueira, K. Boussetta, N. Achir. *2016 IEEE Global Communications Conference, GLOBECOM 2016, Washington, DC, USA, December 4-8, 2016*, 2016. [doi](https://doi.org/10.1109/GLOCOM.2016.7841618)
1. [Conference]{.pubtype .conf} **A new security games based reaction algorithm against DOS attacks in VANETs**. M. N. Mejri, N. Achir, M. Hamdi. *13th IEEE Annual Consumer Communications \& Networking Conference, CCNC 2016, Las Vegas, NV, USA, January 9-12, 2016*, 2016. [doi](https://doi.org/10.1109/CCNC.2016.7444896)
1. [Conference]{.pubtype .conf} **A new group Diffie-Hellman key generation proposal for secure VANET communications**. M. N. Mejri, N. Achir, M. Hamdi. *13th IEEE Annual Consumer Communications \& Networking Conference, CCNC 2016, Las Vegas, NV, USA, January 9-12, 2016*, 2016. [doi](https://doi.org/10.1109/CCNC.2016.7444925)
1. [Conference]{.pubtype .conf} **A Heuristic Path Planning Approach for UAVs Integrating Tracking Support Through Terrestrial Wireless Networks**. M. Bekhti, N. Achir, K. Boussetta, M. Abdennebi. *Smart Objects and Technologies for Social Good - Second International Conference, GOODTECHS 2016, Venice, Italy, November 30 - December 1, 2016, Proceedings*, 2016. [doi](https://doi.org/10.1007/978-3-319-61949-1\_23)

## 2015

### Journal articles
1. [Journal]{.pubtype .journal} **WLAN planning: Separate and joint optimization of both access point placement and channel assignment**. A. Farsi, N. Achir, K. Boussetta. *Ann. des T\'el\'ecommunications*, 2015. [doi](https://doi.org/10.1007/S12243-014-0447-2)

## 2014

### Journal articles
1. [Journal]{.pubtype .journal} **Planning and Deployment of Wireless Sensor Networks**. R. Boutaba, N. Achir, M. St-Hilaire, E. F. Nakamura. *Int. J. Distributed Sens. Networks*, 2014. [doi](https://doi.org/10.1155/2014/198139)

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Optimized broadcast scheme for mobile ad hoc networks**. A. Amari, N. Achir, P. M\"uhlethaler, A. Laouiti. *IEEE Wireless Communications and Networking Conference, WCNC 2014, Istanbul, Turkey, April 6-9, 2014*, 2014. [doi](https://doi.org/10.1109/WCNC.2014.6952817)
1. [Conference]{.pubtype .conf} **Optimal sinks deployment and packet scheduling for Wireless Sensor Networks**. N. Achir, P. M\"uhlethaler. *2014 IFIP Wireless Days, WD 2014, Rio de Janeiro, Brazil, November 12-14, 2014*, 2014. [doi](https://doi.org/10.1109/WD.2014.7020827)
1. [Conference]{.pubtype .conf} **Massive MIMO cooperative communications for wireless sensor networks: Throughput and energy efficiency analysis**. N. Achir, M. Debbah, P. M\"uhlethaler. *25th IEEE Annual International Symposium on Personal, Indoor, and Mobile Radio Communication, PIMRC 2014, Washington DC, USA, September 2-5, 2014*, 2014. [doi](https://doi.org/10.1109/PIMRC.2014.7136234)

## 2013

### Journal articles
1. [Journal]{.pubtype .journal} **Multipath traffic balancing approach for disconnection reduction in video games over mobile ad hoc networks**. A. Kaiser, N. Achir, K. Boussetta. *Wirel. Commun. Mob. Comput.*, 2013. [doi](https://doi.org/10.1002/WCM.2211)

## 2012

### Journal articles
1. [Journal]{.pubtype .journal} **Foreword to the special issue on wireless network: from home to backbone**. N. Achir, H. Gacanin, O. C. M. B. Duarte. *Telecommun. Syst.*, 2012. [doi](https://doi.org/10.1007/S11235-011-9418-3)

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Vehicular Ad-hoc Networks using slotted Aloha: Point-to-point, emergency and broadcast communications**. B. Blaszczyszyn, P. M\"uhlethaler, N. Achir. *Proceedings of the IFIP Wireless Days Conference 2012, Ireland, November 21-23, 2012*, 2012. [doi](https://doi.org/10.1109/WD.2012.6402813)
1. [Conference]{.pubtype .conf} **Three-phase heuristic algorithm for Wireless LAN planning**. A. Farsi, N. Achir, K. Boussetta. *2012 IEEE Wireless Communications and Networking Conference, WCNC 2012, Paris, France, April 1-4, 2012*, 2012. [doi](https://doi.org/10.1109/WCNC.2012.6214176)
1. [Conference]{.pubtype .conf} **Backhaul Topology Design and Weighted Max-Min Fair Capacity Allocation in Wireless Mesh Networks**. A. Farsi, N. Achir, K. Boussetta, G. Diaz, A. Gomez. *Advanced Infocomm Technology - 5th IEEE International Conference, ICAIT 2012, Paris, France, July 25-27, 2012. Revised Papers*, 2012. [doi](https://doi.org/10.1007/978-3-642-38227-7\_32)
1. [Conference]{.pubtype .conf} **Adaptive Contention Window for Zone-Based Dissemination of Vehicular Traffic**. A. Gomez, G. Diaz, K. Boussetta, N. Achir, A. Farsi. *Advanced Infocomm Technology - 5th IEEE International Conference, ICAIT 2012, Paris, France, July 25-27, 2012. Revised Papers*, 2012. [doi](https://doi.org/10.1007/978-3-642-38227-7\_35)

## 2011

### Journal articles
1. [Journal]{.pubtype .journal} **Mobile WiMAX Bandwidth Reservation Thresholds: A Heuristic Approach**. S. Khemiri, K. Boussetta, N. Achir, G. Pujolle. *Int. J. Wirel. Networks Broadband Technol.*, 2011. [doi](https://doi.org/10.4018/IJWNBT.2011040105)
1. [Journal]{.pubtype .journal} **Artificial potential field approach in WSN deployment: Cost, QoM, connectivity, and lifetime constraints**. N. Aitsaadi, N. Achir, K. Boussetta, G. Pujolle. *Comput. Networks*, 2011. [doi](https://doi.org/10.1016/J.COMNET.2010.07.017)

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Use case description of VPAIR: Virtual Police Agents for traffic guidance**. A. Gomez, G. Diaz, K. Boussetta, N. Achir. *Global Information Infrastructure Symposium - GIIS 2011*, 2011. [doi](https://doi.org/10.1109/GIIS.2011.6026704)
1. [Conference]{.pubtype .conf} **Heuristic approaches for access points deployment and Frequency Assignment in WLANs**. A. Farsi, N. Achir, K. Boussetta. *Global Information Infrastructure Symposium - GIIS 2011*, 2011. [doi](https://doi.org/10.1109/GIIS.2011.6026713)
1. [Conference]{.pubtype .conf} **Effects of packetization delay on multiplayer gaming experience over ad hoc networks**. K. Boussetta, A. Kaiser, N. Achir. *Proceedings of the IFIP Wireless Days Conference 2011, Niagara Falls, ON, Canada, October 10-12, 2011*, 2011. [doi](https://doi.org/10.1109/WD.2011.6098224)
1. [Conference]{.pubtype .conf} **An Energy-Delay Routing Protocol for Video Games over Multihops Ad Hoc Networks**. A. Kaiser, K. Boussetta, N. Achir. *Ad Hoc Networks - Third International ICST Conference, ADHOCNETS 2011, Paris, France, September 21-23, 2011, Revised Selected Papers*, 2011. [doi](https://doi.org/10.1007/978-3-642-29096-1\_14)

## 2010

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Multi-Objective WSN Deployment: Quality of Monitoring, Connectivity and Lifetime**. N. Aitsaadi, N. Achir, K. Boussetta, G. Pujolle. *Proceedings of IEEE International Conference on Communications, ICC 2010, Cape Town, South Africa, 23-27 May 2010*, 2010. [doi](https://doi.org/10.1109/ICC.2010.5502276)
1. [Conference]{.pubtype .conf} **Improving Energy Efficiency and Gameplay Fairness for Time-Sensitive Multiplayers Games in MANET**. A. Kaiser, N. Achir, K. Boussetta. *2010 IEEE International Conference on Communications Workshops*, 2010. [doi](https://doi.org/10.1109/ICCW.2010.5503904)
1. [Conference]{.pubtype .conf} **A preliminary evaluation of backup servers for longer gaming sessions in MANETs**. C. E. Palazzi, A. Kaiser, N. Achir, K. Boussetta. *3rd International Conference on Simulation Tools and Techniques, SIMUTools '10, Malaga, Spain - March 16 - 18, 2010*, 2010. [doi](https://doi.org/10.4108/ICST.SIMUTOOLS2010.8720)
1. [Conference]{.pubtype .conf} **A multipath traffic balancing proposal to reduce gaming disconnections in MANET**. A. Kaiser, N. Achir, K. Boussetta. *Proceedings of the 3rd IFIP Wireless Days Conference 2010, Venice, Italy, October 20-22, 2010*, 2010. [doi](https://doi.org/10.1109/WD.2010.5657771)
1. [Conference]{.pubtype .conf} **A MAC-level flow control algorithm for H.264/AVC video streaming over HSDPA**. S. Benayoune, N. Achir, K. Boussetta, K. Chen. *Proceedings of the 6th International Wireless Communications and Mobile Computing Conference, IWCMC 2010, Caen, France, June 28 - July 2, 2010*, 2010. [doi](https://doi.org/10.1145/1815396.1815663)
1. [Conference]{.pubtype .conf} **A Combined MAC and Physical Resource Allocation Mechanism in IEEE 802.16e Networks**. S. Khemiri, G. Pujolle, K. Boussetta, N. Achir. *Proceedings of the 71st IEEE Vehicular Technology Conference, VTC Spring 2010, 16-19 May 2010, Taipei, Taiwan*, 2010. [doi](https://doi.org/10.1109/VETECS.2010.5493893)

## 2009

### Journal articles
1. [Journal]{.pubtype .journal} **A Tabu Search WSN Deployment Method for Monitoring Geographically Irregular Distributed Events**. N. Aitsaadi, N. Achir, K. Boussetta, G. Pujolle. *Sensors*, 2009. [doi](https://doi.org/10.3390/S90301625)
1. [Journal]{.pubtype .journal} **A MAC Centric Cross Layer Approach for H.264 Video Streaming over HSDPA**. S. Benayoune, N. Achir, K. Boussetta, K. Chen. *J. Commun.*, 2009. [doi](https://doi.org/10.4304/JCM.4.9.691-699)

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Two-tier Wireless Mesh Networks dimensioning**. A. Farsi, N. Achir, K. Boussetta. *2nd IFIP Wireless Days, WD 2009, Paris, France, December 15-17, 2009*, 2009. [doi](https://doi.org/10.1109/WD.2009.5449654)
1. [Conference]{.pubtype .conf} **Potential Field Approach to Ensure Connectivity and Differentiated Detection in WSN Deployment**. N. Aitsaadi, N. Achir, K. Boussetta, G. Pujolle. *Proceedings of IEEE International Conference on Communications, ICC 2009, Dresden, Germany, 14-18 June 2009*, 2009. [doi](https://doi.org/10.1109/ICC.2009.5199345)
1. [Conference]{.pubtype .conf} **On the Objective Evaluation of Real-Time Networked Games**. A. Kaiser, D. Maggiorini, N. Achir, K. Boussetta. *Proceedings of the Global Communications Conference, 2009. GLOBECOM 2009, Honolulu, Hawaii, USA, 30 November - 4 December 2009*, 2009. [doi](https://doi.org/10.1109/GLOCOM.2009.5426032)
1. [Conference]{.pubtype .conf} **Multiplayer games over wireless ad hoc networks: Energy and delay analysis**. A. Kaiser, N. Achir, K. Boussetta. *Proceedings of the International Conference on Ultra Modern Telecommunications, ICUMT 2009, 12-14 October 2009, St. Petersburg, Russia*, 2009. [doi](https://doi.org/10.1109/ICUMT.2009.5345413)
1. [Conference]{.pubtype .conf} **Capacity Assignment for Multipath Routing in Multiclass Two-Tier Wireless Mesh Networks**. A. Farsi, N. Achir, K. Boussetta. *2009 IEEE Globecom Workshops*, 2009. [doi](https://doi.org/10.1109/GLOCOMW.2009.5360719)

## 2008

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Heuristic Deployment to Achieve Both Differentiated Detection and Connectivity in WSN**. N. Aitsaadi, N. Achir, K. Boussetta, G. Pujolle. *Proceedings of the 67th IEEE Vehicular Technology Conference, VTC Spring 2008, 11-14 May 2008, Singapore*, 2008. [doi](https://doi.org/10.1109/VETECS.2008.38)
1. [Conference]{.pubtype .conf} **Content-Aware ARQ for H.264 Streaming in UTRAN**. S. Benayoune, N. Achir, K. Boussetta, K. Chen. *WCNC 2008, IEEE Wireless Communications \& Networking Conference, March 31 2008 - April 3 2008, Las Vegas, Nevada, USA, Conference Proceedings*, 2008. [doi](https://doi.org/10.1109/WCNC.2008.348)
1. [Conference]{.pubtype .conf} **Bandwidth partitioning for Mobile WiMAX service provisioning**. S. Khemiri, K. Boussetta, N. Achir. *1st IFIP Wireless Days, WD 2008, Dubai, UAE, November 24-27, 2008*, 2008. [doi](https://doi.org/10.1109/WD.2008.4812926)
1. [Conference]{.pubtype .conf} **A Tabu Search Approach for Differentiated Sensor Network Deployment**. N. Aitsaadi, N. Achir, K. Khaled, G. Pujolle. *5th IEEE Consumer Communications and Networking Conference, CCNC 2008, Las Vegas, NV, USA, January 10-12, 2008*, 2008. [doi](https://doi.org/10.1109/CCNC08.2007.43)
1. [Conference]{.pubtype .conf} **A gradient approach for differentiated wireless sensor network deployment**. N. Aitsaadi, N. Achir, K. Boussetta, B. Gavish. *1st IFIP Wireless Days, WD 2008, Dubai, UAE, November 24-27, 2008*, 2008. [doi](https://doi.org/10.1109/WD.2008.4812925)

## 2007

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **WiMax bandwidth provisioning service to residential customers**. S. Khemiri, K. Boussetta, N. Achir, G. Pujolle. *9th IFIP International Conference on Mobile Wireless Communications Networks, MWCN 2007, Cork, Ireland, 19-21 September, 2007*, 2007. [doi](https://doi.org/10.1109/ICMWCN.2007.4668192)
1. [Conference]{.pubtype .conf} **Optimal Call Admission Control for an IEEE 802.16 Wireless Metropolitan Area Network**. S. Khemiri, K. Boussetta, N. Achir, G. Pujolle. *Network Control and Optimization, First EuroFGI International Conference, NET-COOP 2007, Avignon, France, June 5-7, 2007, Proceedings*, 2007. [doi](https://doi.org/10.1007/978-3-540-72709-5\_11)
1. [Conference]{.pubtype .conf} **Optimal Call Admission Control for an IEEE 802.16 Wireless Metropolitan Area Network**. S. Khemiri, K. Boussetta, N. Achir, G. Pujolle. *Network Control and Optimization*, 2007.
1. [Conference]{.pubtype .conf} **M\'ecanismes de gestion de la bande passante pour les r\'eseaux WiMAX**. S. Khemiri, K. Boussetta, N. Achir, G. Pujolle. *8\`eme Colloque Francophone de Gestion de R\'eseaux et de Services, GRES 2007*, 2007.
1. [Conference]{.pubtype .conf} **Differentiated Underwater Sensor Network Deployment**. N. Aitsaadi, N. Achir, K. Boussetta, G. Pujolle. *OCEANS 2007 - Europe*, 2007. [doi](https://doi.org/10.1109/OCEANSE.2007.4302456)
1. [Conference]{.pubtype .conf} **D\'eploiement Diff\'erenci\'e des R\'eseaux de Capteurs**. N. Aitsaadi, N. Achir, K. Boussetta, G. Pujolle. *GRES 2007 - 8\`eme Colloque Francophone de Gestion de R\'eseaux et de Services*, 2007.
1. [Conference]{.pubtype .conf} **Assessment of MANET broadcast schemes in the application context of multiplayer video games**. A. Sardouk, S. Senouci, N. Achir, K. Boussetta. *Proceedings of the 6th Workshop on Network and System Support for Games, NETGAMES 2007, Melbourne, Australia, September 19-20, 2007*, 2007. [doi](https://doi.org/10.1145/1326257.1326267)
1. [Conference]{.pubtype .conf} **A study of H.264/AVC robustness over a wireless link**. S. Benayoune, N. Achir, K. Boussetta, K. Chen. *9th International Symposium on Signal Processing and Its Applications, ISSPA 2007, Sharjah, United Arab Emirates, February 12-15, 2007*, 2007. [doi](https://doi.org/10.1109/ISSPA.2007.4555558)
1. [Conference]{.pubtype .conf} **A Markov Decision Model for Optimal CAC in IEEE 802.16**. K. Boussetta, N. Achir, S. Khemiri. *Networking and Electronic Commerce Research Conference (NAEC)*, 2007.

## 2006

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Performances des m\'ecanismes de robustesse de H.264/AVC sur un lien sans fil**. S. Benayoune, N. Achir, K. Boussetta, K. Chen. *Colloque Francophone sur l'Ing\'enierie des Protocoles - CFIP 2006*, 2006. [pdf](https://inria.hal.science/inria-00110261/file/CFIP-ID-59.pdf)
1. [Conference]{.pubtype .conf} **Modeling Data to Management Dynamic Services Deployment in Autonomic Networks**. G. Diaz, N. Achir, K. Chen. *2006 2nd International Conference on Information \& Communication Technologies*, 2006. [doi](https://doi.org/10.1109/ICTTA.2006.1684966)

## 2005

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Multi-object video error recovery over wireless networks**. N. Achir. *WMuNeP'05 - Proceedings of the First ACM Workshop on Wireless Multimedia Networking and Performance Modeling, Montreal, Quebec, Canada, October 13, 2005*, 2005. [doi](https://doi.org/10.1145/1089737.1089743)

## 2004

### Journal articles
1. [Journal]{.pubtype .journal} **Une nouvelle architecture de gestion de r\'eseaux DiffServ bas\'ee sur la technologie de r\'eseau actif et la gestion \`a base de r\`egles**. M. Fonseca, N. Agoulmine, Y. Ghamri-Doudane, N. Achir, G. Pujolle. *Ann. des T\'el\'ecommunications*, 2004. [doi](https://doi.org/10.1007/BF03179688)
1. [Journal]{.pubtype .journal} **Une nouvelle architecture de contr\^ole de r\'eseaux DiffServ bas\'ee sur la technologie r\'eseau actif et les politiques**. M. S. Fonseca, N. Agoulmine, Y. Ghamri Doudane, N. Achir, G. Pujolle. *Annals of Telecommunications - annales des t\'el\'ecommunications*, 2004. [doi](https://doi.org/10.1007/BF03179688)

## 2003

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Object-based unequal loss protection for multiobject video delivery**. N. Achir, K. Salamation, G. Pujolle. *Proceedings EC-VIP-MC 2003. 4th EURASIP Conference focused on Video/Image Processing and Multimedia Communications (IEEE Cat. No.03EX667)*, 2003. [doi](https://doi.org/10.1109/VIPMC.2003.1220481)
1. [Conference]{.pubtype .conf} **Network-based adaptation for MPEG-4 multicast video delivery**. N. Achir, G. Pujolle. *10th International Conference on Telecommunications, 2003. ICT 2003.*, 2003. [doi](https://doi.org/10.1109/ICTEL.2003.1191648)
1. [Conference]{.pubtype .conf} **Multi-Object Video Rate Control**. N. Achir, G. Pujolle. *Network Control and Engineering for QoS, Security and Mobility II, IFIP TC6 / WG6.2 \& WG6.7 Conference on Network Control and Engineering for QoS (Net-Con 2003), October 13-15, 2003, Muscat, Oman*, 2003.

## 2002

### Conference & workshop papers
1. [Conference]{.pubtype .conf} **Active Technology as an Efficient Approach to Control DiffServ Networks: The DACA Architecture**. N. Achir, N. Agoulmine, M. Fonseca, Y. Ghamri-Doudane, G. Pujolle. *Management of Multimedia on the Internet, 5th IFIP/IEEE International Conference on Management of Multimedia Networks and Services, MMNS 2002, Santa Barbara, CA, USA, October 6-9, 2002, Proceedings*, 2002. [doi](https://doi.org/10.1007/3-540-45812-3\_14)
1. [Conference]{.pubtype .conf} **Active Technology as an Efficient Approach to Control DiffServ Networks: The DACA Architecture**. N. Achir, N. Agoulmine, M. Fonseca, Y. Ghamri-Doudane, G. Pujolle. *Management of Multimedia on the Internet*, 2002.

## 2000

### Journal articles
1. [Journal]{.pubtype .journal} **Active Networking System Evaluation: a Pratical Experience**. N. Achir, M. Fonseca, Y. Ghamri-Doudane, N. Agoulmine, A. Mehaoua. *Networking and Information Systems Journal*, 2000.
1. [Journal]{.pubtype .journal} **Active bandwidth sharing for multi-layered video in multi-source environments**. N. Achir, M. Dias de Amorim, O. C. Muniz Bandeira Duarte, G. Pujolle. *Network Information System Journal*, 2000.

<!-- /references -->







